imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_mongodb:
    connections:
        default:
            server: "%mongo_server%"
            options: {}
    default_database: "%mongo_database%"
    document_managers:
        default:
            auto_mapping: true

auto_ria:
    api:
      host: "%auto_ria_api_host%"
      dictionaries_endpoints:
        categories:
          self: "%auto_ria_categories_endpoint%"
          bodystyles: "%auto_ria_bodystyles_endpoint%"
          marks:
            self: "%auto_ria_marks_endpoint%"
            models: "%auto_ria_models_endpoint%"
          gearboxes: "%auto_ria_api_gearboxes_endpoint%"
          driver_types: "%auto_ria_api_driver_types_endpoint%"
          options: "%auto_ria_api_options_endpoint%"
        states:
          self: "%auto_ria_states_endpoint%"
          cities: "%auto_ria_api_cities_endpoint%"
        fuels: "%auto_ria_api_fuels_endpoint%"
        colors: "%auto_ria_api_colors_endpoint%"
      model_mapping:
        categories: Category
        bodystyles: BodyStyle
        marks: Brand
        models: Model
        gearboxes: Gearbox
        driver_types: DriverType
        options: Option
        states: Region
        cities: City
        fuels: FuelType
        colors: Color
